name: Backend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Шаг клонирует код репозитория для последующих действий

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Настраивает Docker Buildx, позволяющий кросс-платформенные сборки Docker-образов

      - name: Build backend Docker image
        run: |
          docker build -t backend-test ./fullstack_backend
        # Сборка Docker-образа для бэкенда в директории fullstack_backend
